kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "frontend.labels" . | nindent 4}}
spec:
  ports:
    - nodePort: 30170
      port: {{ .Values.service.port }}
      targetPort: {{.Values.service.targetPort }}
      protocol: TCP
  selector:
    {{ include "frontend.selectorLabels" . | nindent 4}}
  type: {{ .Values.service.type }}
